timeout 1
default MyOS
menu title Boot the OS

label MyOS
	kernel /vmlinuz-7.0.2-msm8937
	fdt /dtbs/7.0.2-msm8937/qcom/msm8937-xiaomi-land.dtb
	initrd /initrd.img-7.0.2-msm8937
	append console=tty0 root=PARTUUID=2fc3ff08-58af-3268-8d94-28ce07d79c0c rw loglevel=3 splash
