name: Cleanup all workflow runs

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all completed workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

          retain_days: 0
          keep_minimum_runs: 0

          delete_workflow_pattern: ".*"

          delete_workflow_by_state_pattern: completed

          delete_run_by_conclusion_pattern: success|failure|cancelled
