name: Cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete all but the latest run
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          workflows=$(gh workflow list --json name -q '.[].name')
          for workflow in $workflows; do
            run_ids=$(gh run list --workflow "$workflow" --json databaseId --jq '.[1:].databaseId | .[]')
            for id in $run_ids; do
              gh run delete "$id"
            done
          done
